ported to 8.11. added the genLensN function
bedrocksystems/coq-lens pull request #7
Opened 2020-03-21 03:10 UTC by aa755

2020-03-26 19:47 UTC, gmalecha commented on theories/TC/TC.v
> +Record Info : Type :=
This is odd, the `Set` is already removed in master.

2020-03-26 19:49 UTC, aa755 commented on theories/TC/TC.v
> +Record Info : Type :=
this MR was made many days ago

2020-03-26 19:50 UTC, aa755 commented on theories/TC/TC.v
> +Record Info : Type :=
However, I don't see why the template coq syntax stuff doesn't live in `Set`

2020-03-26 19:54 UTC, gmalecha requested changes

2020-03-26 19:54 UTC, gmalecha commented on theories/TC/TC.v
> +  in
Can you remove the duplicate code here?

2020-03-26 19:54 UTC, gmalecha commented on theories/TC/TC.v
> +Record Info : Type :=
I didn't see it when I was updating things this morning. I guess that github doesn't update diffs.

2020-03-26 19:56 UTC, gmalecha commented on theories/TC/TC.v
> +          print_nf ("info: the constructor " ++ ctor_name ++ " has no projections but an arity of " ++ (MCString.string_of_nat ctor_arity) ++ ". Perhaps you forgot to enable primitive projections bef
Do you prefer an error here, or just a message? If we change to back to just a message, we need to fix the test suite.

2020-03-26 20:53 UTC, gmalecha commented on theories/TC/TC.v
> +Record Info : Type :=
The AST no longer lives in `Set` because of universes (universe instances) which are sorted sets (represented with a subset type).

2020-03-26 21:01 UTC, aa755 commented on theories/TC/TC.v
> +Record Info : Type :=
Universes are ultimately just natural numbers. I don't see the syntax doesn't fit in Set.

2020-03-27 00:23 UTC, merged

2020-03-27 03:07 UTC, aa755 commented on theories/TC/TC.v
> +        else ret t
`t` --> `tt`?

2020-03-27 03:52 UTC, gmalecha commented on theories/TC/TC.v
> +Record Info : Type :=
See https://github.com/MetaCoq/metacoq/pull/383

2020-03-27 04:13 UTC, gmalecha commented on theories/TC/TC.v
> +        else ret t
Fixed.